name: Mise - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          sparse-checkout: |
            .github/actions/mise-project-setup
            mise.toml

      - name: Prepare cache
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: "prepare"
