name: Mise - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          sparse-checkout: |
            .github/actions/mise-project-setup
            mise.toml

      - name: Prepare cache
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: "prepare"
