name: Mise - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            .github/actions/mise-project-setup
            mise.toml

      - name: Prepare cache
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: "prepare"
