name: Mise task
on:
  workflow_call:
    inputs:
      task:
        description: Task to run
        required: true
        type: string
permissions:
  contents: read

jobs:
  task:
    name: Mise task - ${{ inputs.task }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Install tools
        uses: ./.github/actions/mise-project-setup

      - name: Run task - ${{ inputs.task }}

        env:
          MISE_TASK: ${{ inputs.task }}
        run: mise run "${MISE_TASK}"
        shell: bash
