name: Mise - prepare cache
on:
  workflow_call:
permissions:
  contents: read

jobs:
  prepare-cache:
    name: Prepare Mise cache
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: |
            .github/actions/mise-project-setup
            mise.toml

      - name: Prepare cache
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: "prepare"
